name: Buil App

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    
jobs:
  BuildAndroid:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x.x
        
    - uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '11'
          
    - name: Install MAUI Workloads
      run: |
        dotnet workload install android --ignore-failed-sources
        dotnet workload install maui --ignore-failed-sources

    - name: Build with dotnet core
      run: dotnet build Maui.Ideas.App.sln --configuration Release
      
  UnitTests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Run dotnet test
      run: dotnet test Maui.Ideas.App.Tests/Maui.Ideas.App.Tests.csproj -v --configuration Debug
